uni_name: cmu
take_id: take_0
data_dir: "/private/home/miguelmartin/ego4d/ego4d_public/data_experiments"
name: null
aria_fps: 30
exo_fps: null
mobile_fps: null
include_aria: true
sync_exo_views: false
aria_use_sync_info: false
aria_last_walkthrough_sec: null
use_gpu: true
rot_mode: 0
exo_from_frame: null
exo_to_frame: null
frame_rate: 0.5
exo1_frames:
  - 100
  - 200
exo2_frames:
  - 30
  - 20
exo3_frames:
  - 5
  - 10
exo4_frames:
  - 11
  - 50
mobile_frames:
  - 1
  - 2
  - 3
  - 4
aria_frames:
  - 100
  - 500
run_colmap: false
colmap_bin: null
vrs_bin: null
force_download: false
