uni_name: sfu
take_id: 1a69642e-93d6-4faa-93df-72ee253bced5
data_dir: "/private/home/miguelmartin/ego4d/ego4d_public/data_experiments"
name: null
aria_fps: 30
exo_fps: null
mobile_fps: null
include_aria: true
sync_exo_views: false
aria_use_sync_info: false
aria_last_walkthrough_sec: null
use_gpu: true
rot_mode: 0
exo_from_frame: 200
exo_to_frame: 300
frame_rate: 0.5
exo1_frames: null
exo2_frames: null
exo3_frames: null
exo4_frames: null
mobile_frames: null
aria_frames: null
colmap_bin: null
vrs_bin: null
run_colmap: false
force_download: false
