root_dir: "/private/home/miguelmartin/ego4d/ego4d_public/colmap_experiments/"
gpu_id: 0
mode: "preprocess"
inputs:
  from_frame_number: 7000
  to_frame_number: 7599
  metadata_json_path: "s3://ego4d-consortium-sharing/internal/egoexo_pilot/iu/bike/metadata.json"
  aria_trajectory_path: "s3://ego4d-consortium-sharing/internal/temple3_egoexo/iu_bike_nopointcloud/closed_loop_trajectory.csv"
  exo_trajectory_path: "s3://ego4d-consortium-sharing/internal/temple3_egoexo/iu_bike_nopointcloud/gopro_calibs.csv"
  aria_streams:
    - 214-1
    - 1201-1
    - 1201-2
  exo_timesync_name_to_calib_name:
    cam01: "GX010017"
    cam02: "GX010005"
    cam03: "GX010007"
    cam04: "GX010009"
mode_preprocess:
  dataset_name: "dataset"
  vrs_bin_path: "vrs"
  download_video_files: true
  force_download: false
  extract_all_aria_frames: false
mode_bbox:
  detector_model_config: "/private/home/miguelmartin/ego4d/ego4d_public/tp/mmdetection/configs/faster_rcnn/faster_rcnn_x101_64x4d_fpn_1x_coco.py"
  detector_model_checkpoint: "https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_x101_64x4d_fpn_1x_coco/faster_rcnn_x101_64x4d_fpn_1x_coco_20200204-833ee192.pth"
  use_aria_trajectory: true
mode_pose_estimation:
  pose_model_config: "/private/home/miguelmartin/ego4d/ego4d_public/tp/mmpose/configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/hrnet_w48_coco_wholebody_384x288_dark_plus.py"
  pose_model_checkpoint: "https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_wholebody_384x288_dark-f5726563_20200918.pth"
mode_triangulate:
  todo: abc

